number = set()
n1 = int(input("Enter number: "))
number.add(n1)
n2 = int(input("Enter number: "))
number.add(n2)
n3 = int(input("Enter number: "))
number.add(n3)
n4 = int(input("Enter number: "))
number.add(n4)
n5 = int(input("Enter number: "))
number.add(n5)
n6 = int(input("Enter number: "))
number.add(n6)
n7= int(input("Enter number: "))
number.add(n7)
n8 = int(input("Enter number: "))
number.add(n8)

print(number)